### ISSUE TITLE
Skeleton WP template

### ISSUE THREAD

**Issue by timharek** [srib-dev/srib.no#2]
Et veldig barebone template som vi kan enkelt bygge på, helst responsivt.

**Comment by tse018** [comment]
https://freewebsitetemplates.com/preview/familychessclub/index.html

https://freewebsitetemplates.com/preview/musicartistwebtemplate/index.html

**Comment by tse018** [comment]
2 templates som vi kan ta utgangspunkt i

https://freewebsitetemplates.com/preview/musicartistwebtemplate/index.html

https://freewebsitetemplates.com/preview/familychessclub/index.html

**Comment by timharek** [comment]
> 2 templates som vi kan ta utgangspunkt i
> 
> https://freewebsitetemplates.com/preview/musicartistwebtemplate/index.html
> 
> https://freewebsitetemplates.com/preview/familychessclub/index.html

Disse er verken responsive eller for WordPress. Disse kan vi dessverre ikke bruke.

**Comment by tse018** [comment]
Aahh crap

**Comment by timharek** [comment]
Her er noen open source alternativer:

- https://github.com/understrap/understrap
- https://github.com/roots/sage
- https://github.com/tonik/theme
- https://github.com/Rareloop/lumberjack

**Comment by timharek** [comment]
Går for denne: https://github.com/understrap/understrap
